dataset = 
[
  {
    "id": "0YDS9EBJLVAB",
    "shortname": "Bee★R B5",
    "description": "No doubt inspired by the Nismo LMGT4, the Bee★R B5 offered great style at an affordable price due to their cast construction. The twin valve stems allow quick and easy nitrogren filling.",
    "brand": "Bee★R",
    "model": "B5",
    "manufacturer": "Unverified",
    "year_start": "Unverified",
    "year_end": "Unverified",
    "origin": "Unverified",
    "construction": "1 Piece - Cast",
    "style": "5 Spoke",
    "link": "https://web.archive.org/web/20100116090507/http://www.bee-r.com/main/parts/wheel/index.htm",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+25", "colors": "White, Silver, Bronze, Chrome"},
      {"diameter": "18", "width": "9.5", "pcd": "5x114.3", "offsets": "+25/+38", "colors": "White, Silver, Bronze, Chrome"}
    ],
    "related": []
  },
  {
    "id": "U4VL4KJ2P2SV",
    "shortname": "B.I.M. Down Hill Special ae031",
    "description": "A forged split 6 spoke wheel from Bridgestone's B.I.M Creative Studio. Extremely similar in appearance to the cast <a onclick='loadDetails(&quot;X7MDK0WHI5JM&quot;)'>Bridgestone ae033</a> but most easily identified by the small webs between the spokes near the hub section which are absent from the ae033.",
    "brand": "B.I.M. Creative Studio",
    "model": "Down Hill Special ae031",
    "manufacturer": "SuperAlloy Industrial Co., Ltd",
    "year_start": "2003",
    "year_end": "2003",
    "origin": "Taiwan",
    "construction": "1 Piece - Forged",
    "style": "Split 6 Spoke",
    "link": "https://web.archive.org/web/20050213145059/http://bim-cs.com/products/dhs/ae031/size.html",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg"],
    "sizes": [
      {"diameter": "17", "width": "7.0", "pcd": "4x100", "offsets": "+38/+48", "colors": "Bronze, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "4x114.3", "offsets": "+38/+48", "colors": "Bronze, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+38/+48", "colors": "Bronze, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+38/+48", "colors": "Bronze, Gunmetal"}
    ],
    "related": ["X7MDK0WHI5JM"]
  },
  {
    "id": "DV3YB9P4LFDL",
    "shortname": "B.I.M. Down Hill Special ae032",
    "description": "A forged 6 spoke wheel from Bridgestone's B.I.M Creative Studio. Very similar in appearance to the cast <a onclick='loadDetails(&quot;SL7DDCFW05QZ&quot;)'>Bridgestone ae034</a> but most easily identified by its hub section which features a machined center with harder edges than the ae034 and weight saving holes between the lug holes.",
    "brand": "B.I.M. Creative Studio",
    "model": "Down Hill Special ae032",
    "manufacturer": "SuperAlloy Industrial Co., Ltd",
    "year_start": "2003",
    "year_end": "2003",
    "origin": "Taiwan",
    "construction": "1 Piece - Forged",
    "style": "6 Spoke",
    "link": "https://web.archive.org/web/20050213145059/http://bim-cs.com/products/dhs/ae032/size.html",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "17", "width": "7.0", "pcd": "4x100", "offsets": "+38/+48", "colors": "Gunmetal, Gold"},
      {"diameter": "17", "width": "7.0", "pcd": "4x114.3", "offsets": "+38/+48", "colors": "Gunmetal, Gold"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+38/+48", "colors": "Gunmetal, Gold"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+38/+48", "colors": "Gunmetal, Gold"}
    ],
    "related": ["SL7DDCFW05QZ"]
  },
  {
    "id": "X7MDK0WHI5JM",
    "shortname": "B.I.M. Down Hill Special ae033",
    "description": "A cast split 6 spoke wheel from Bridgestone's B.I.M Creative Studio. Though not as strong or light as the forged <a onclick='loadDetails(&quot;U4VL4KJ2P2SV&quot;)'> Bridgestone ae031</a> that it shares it's design with, it is offered in a much larger array of sizes.",
    "brand": "B.I.M. Creative Studio",
    "model": "Down Hill Special ae033",
    "manufacturer": "Enkei Co., Ltd.",
    "year_start": "2004",
    "year_end": "2009",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "Split 6 Spoke",
    "link": "https://web.archive.org/web/20050213145059/http://bim-cs.com/products/dhs/ae033/size.html",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+30/+38/+42", "colors": "Gold, Gunmetal"},
      {"diameter": "15", "width": "6.5", "pcd": "4x114.3", "offsets": "+42", "colors": "Gold, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+30/+38/+42", "colors": "Gold, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+30/+42", "colors": "Gold, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+30/+48", "colors": "Gold, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+30/+38/+42/+48", "colors": "Gold, Gunmetal"},
      {"diameter": "16", "width": "8.0", "pcd": "5x114.3", "offsets": "+30/+38/+44", "colors": "Gold, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "4x100", "offsets": "+38/+44", "colors": "Gold, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "4x114.3", "offsets": "+38/+44", "colors": "Gold, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+30/+38/+48", "colors": "Gold, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+38/+48", "colors": "Gold, Gunmetal"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+30/+36/+44", "colors": "Gold, Gunmetal"},
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+38/+48", "colors": "Gold, Gunmetal"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+38/+48", "colors": "Gold, Gunmetal"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+32/+36/+46", "colors": "Bronze, Gunmetal"}
    ],
    "related": ["U4VL4KJ2P2SV"]
  },
  {
    "id": "SL7DDCFW05QZ",
    "shortname": "B.I.M. Down Hill Special ae034",
    "description": "A cast 6 spoke wheel from Bridgestone's B.I.M Creative Studio. Though not as strong or light as the forged <a onclick='loadDetails(&quot;DV3YB9P4LFDL&quot;)'>Bridgestone ae032</a> that it shares it's design with, it is offered in a much larger array of sizes.",
    "brand": "B.I.M. Creative Studio",
    "model": "Down Hill Special ae034",
    "manufacturer": "Enkei Co., Ltd.",
    "year_start": "2004",
    "year_end": "2009",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "6 Spoke",
    "link": "https://web.archive.org/web/20050213145059/http://bim-cs.com/products/dhs/ae034/size.html",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg","06.jpg"],
    "sizes": [
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+30/+38/+42", "colors": "White, Gunmetal"},
      {"diameter": "15", "width": "6.5", "pcd": "4x114.3", "offsets": "+42", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+30/+38/+42", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+30/+42", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+30/+48", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+30/+38/+42/+48", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "8.0", "pcd": "5x114.3", "offsets": "+30/+38/+44", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "4x100", "offsets": "+38/+44", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "4x114.3", "offsets": "+38/+44", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+30/+38/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+38/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+30/+36/+44", "colors": "White, Gunmetal"},
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+38/+48", "colors": "White, Gunmetal"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+38/+48", "colors": "White, Gunmetal"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+32/+36/+46", "colors": "White, Gunmetal"}
    ],
    "related": ["DV3YB9P4LFDL"]
  },
  {
    "id": "RDU6O6EAMBRF",
    "shortname": "B.I.M. Down Hill Special ae051",
    "description": "",
    "brand": "B.I.M. Creative Studio",
    "model": "Down Hill Special ae051",
    "manufacturer": "Unverified",
    "year_start": "Unverified",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "7 Spoke",
    "link": "https://web.archive.org/web/20081119135952/http://www.bim-cs.com/products/dhs/ae051/size.html",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "14", "width": "5.0", "pcd": "4x100", "offsets": "+43", "colors": "Silver, Bronze"},
      {"diameter": "15", "width": "5.0", "pcd": "4x100", "offsets": "+43", "colors": "Silver, Bronze"},
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+35/+44", "colors": "White, Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+30/+44", "colors": "Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+38", "colors": "White, Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+30/+38/+44", "colors": "Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+38", "colors": "Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+48", "colors": "White, Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+30/+38/+44", "colors": "Silver, Bronze"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+48", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "7.0", "pcd": "4x100", "offsets": "+38/+43", "colors": "Silver, Bronze"},
      {"diameter": "17", "width": "7.0", "pcd": "4x114.3", "offsets": "+31/+38/+43", "colors": "Silver, Bronze"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+38", "colors": "Silver, Bronze"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+48", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+31/+38/+43", "colors": "Silver, Bronze"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+48", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "8.0", "pcd": "4x114.3", "offsets": "+44", "colors": "Silver, Bronze"},
      {"diameter": "17", "width": "8.0", "pcd": "5x100", "offsets": "+34", "colors": "Silver, Bronze"},
      {"diameter": "17", "width": "8.0", "pcd": "5x100", "offsets": "+44", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+34", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+44", "colors": "Silver, Bronze"}
    ],
    "related": []
  },
  {
    "id": "NROW8INOVB8S",
    "shortname": "B.I.M. Down Hill Special ae081",
    "description": "Designed by Blest and sold by New Rayton as the <a onclick='loadDetails(&quot;TGKY3WIFFEH7&quot;)'>EuroMagic GT-08F</a>, the Down Hill Special ae081 combines a cast disk with a flow forming process to form the rim, providing a balance of high strength, light weight, and low cost.",
    "brand": "B.I.M. Creative Studio",
    "model": "Down Hill Special ae081",
    "manufacturer": "Unverified",
    "year_start": "Unverified",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "8 Spoke",
    "link": "https://web.archive.org/web/20081226155838/http://www.bim-cs.com/products/dhs/ae081/size.html",
    "images": ["01.jpg","02.jpg"],
    "sizes": [
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+50", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+48", "colors": "White, Silver, Bronze"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+40/+48/+52", "colors": "White, Silver, Bronze"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+38/+48/+54", "colors": "White, Silver, Bronze"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+38/+45", "colors": "White, Silver, Bronze"}
    ],
    "related": ["TGKY3WIFFEH7"]
  },
  {
    "id": "PC4IC5FMAA11",
    "shortname": "Hinodex Aguzze S-07",
    "description": "Sharing it's silhouette with the bigger and forged <a onclick='loadDetails(&quot;KQZIWHYAJB95&quot;)'>S-07R</a>, the S-07 still offered great performance at a reduced cost due to its cast construction.",
    "brand": "Hinodex",
    "model": "Aguzze S-07",
    "manufacturer": "Unverified",
    "year_start": "1999",
    "year_end": "2001",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "7 Spoke",
    "link": "https://web.archive.org/web/20011206111532/http://www.hinodex.co.jp/catalog/lineup/aguzze/s-07.htm",
    "images": ["01.jpg","02.jpg"],
    "sizes": [
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+25/+35/+43", "colors": "White, Silver"},
      {"diameter": "15", "width": "7.0", "pcd": "4x114.3", "offsets": "+35/+43", "colors": "White, Silver"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+35/+43", "colors": "White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+32/+43", "colors": "White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+32/+43", "colors": "White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+43", "colors": "White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+32/+43", "colors": "White, Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "4x114.3", "offsets": "+30", "colors": "White, Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "5x114.3", "offsets": "+15/+30", "colors": "White, Silver"}
    ],
    "related": ["KQZIWHYAJB95"]
  },
  {
    "id": "KQZIWHYAJB95",
    "shortname": "Hinodex Aguzze S-07R",
    "description": "When it came to their flagship sports wheel, Hinodex tapped Tan-ei-sya to manufacture the S-07R. The resulting wheel was incredibly light, the the heaviest size in the lineup (18x9.5 +15) weighing just 8.2 kg (18.1 lbs) .",
    "brand": "Hinodex",
    "model": "Aguzze S-07R",
    "manufacturer": "Tan-ei-sya Co., Ltd.",
    "year_start": "1999",
    "year_end": "2001",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "7 Spoke",
    "link": "https://web.archive.org/web/20011206112434/http://www.hinodex.co.jp/catalog/lineup/aguzze/s-07r.htm",
    "images": ["01.jpg","02.jpg"],
    "sizes": [
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+40", "colors": "White, Gold"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+47", "colors": "White, Gold"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+34/+47", "colors": "White, Gold"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+32/+36/+40", "colors": "White, Gold"},
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+15/+35/+40", "colors": "White, Gold"},
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+48", "colors": "White, Gold"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+34/+40/+48", "colors": "White, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+33/+35/+40", "colors": "White, Gold"},
      {"diameter": "18", "width": "9.5", "pcd": "5x114.3", "offsets": "+15/+35/+40", "colors": "White, Gold"}
    ],
    "related": ["PC4IC5FMAA11"]
  },
  {
    "id": "T8HREQGJ1TRN",
    "shortname": "Ings TS06",
    "description": "Ings and Rays designed the TS06 with possible use in the Super-Taikyu race series in mind. A forged single piece structure and a twin 6 spoke were chosen to accomplish that goal. The end result is a strong and lightweight wheel well-suited for both the street and the racetrack.",
    "brand": "Ings",
    "model": "TS06",
    "manufacturer": "Rays Co., Ltd.",
    "year_start": "2007",
    "year_end": "2007",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "Split 6 Spoke",
    "link": "https://web.archive.org/web/20231001182932/www.ings-net.com/english/products/wheel.html",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg","06.jpg","07.jpg","08.jpg","09.jpg","10.jpg","11.jpg","12.jpg","13.jpg","14.jpg","15.jpg"],
    "sizes": [
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+43/+48", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+43/+48", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "8.0", "pcd": "5x100", "offsets": "+38/+43", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "8.0", "pcd": "5x114.3", "offsets": "+38/+43", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x100", "offsets": "+43", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+22/+30/+38", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+43", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "9.0", "pcd": "5x114.3", "offsets": "+35/+50", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "9.5", "pcd": "5x114.3", "offsets": "+12/+22/+34/+40", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "10.5", "pcd": "5x114.3", "offsets": "+15/+22", "colors": "Silver, Gunmetal"}
    ],
    "related": []
  },
  {
    "id": "5AL43E793L5Q",
    "shortname": "Modex KS-CE",
    "description": "Keiichi Tsuchiya's signature model wheel. Modex developed these wheels with input from the Drift King himself and contracted Tan-ei-sya to manufacture them and managed to produce an ulta-lightweight wheel.",
    "brand": "Modex",
    "model": "KS-CE",
    "manufacturer": "Tan-ei-sya Co., Ltd.",
    "year_start": "1994",
    "year_end": "2003",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "5 Spoke",
    "link": "https://web.archive.org/web/20031215023958/http://www.modex.co.jp/catalog_tutiya.htm",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "6.5", "pcd": "4x114.3", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "6.5", "pcd": "5x100", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "6.5", "pcd": "5x114.3", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "7.0", "pcd": "4x114.3", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "7.0", "pcd": "5x100", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+30/+35/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "4x100", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "4x114.3", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "5x100", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "5x114.3", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "7.0", "pcd": "4x100", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "7.0", "pcd": "4x114.3", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "8.0", "pcd": "4x100", "offsets": "+20/+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "8.0", "pcd": "4x114.3", "offsets": "+20/+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "8.0", "pcd": "5x100", "offsets": "+20/+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+20/+32/+45", "colors": "Pearl White, Silver"},
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+20/+38/+45", "colors": "Pearl White, Silver"}
    ],
    "related": []
  },
  {
    "id": "GKHP1BHIO41L",
    "shortname": "Mugen MC10L",
    "description": "Inspired by the classic MF10L competition wheel, the new cast aluminum MC10L combines visual appeal with Mugen's signature styling. To meet the rigorous demands of track use, the MC10L features an anti-skid offset flange to improve tire adhesion and a spoke profile that provides clearance for large brake systems.",
    "brand": "Mugen",
    "model": "MC10L",
    "manufacturer": "Cherubim-Alloy Industry Co., Ltd.",
    "year_start": "2022",
    "year_end": "2022",
    "origin": "Taiwan",
    "construction": "1 Piece - Cast",
    "style": "Split 5 Spoke",
    "link": "https://web.archive.org/web/20220215105154/mugen-power.com/english/news/detail/id=1179",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg","06.jpg"],
    "sizes": [
      {"diameter": "15", "width": "8.0", "pcd": "4x100", "offsets": "+32", "colors": "White"},
      {"diameter": "15", "width": "8.0", "pcd": "5x114.3", "offsets": "+32", "colors": "White"}
    ],
    "related": ["N9DRWPB887A0"]
  },
  {
    "id": "N9DRWPB887A0",
    "shortname": "Mugen MF10L",
    "description": "Mugen MF series of forged wheels expertly combined  light weight, strength, and precision with a timeless design. The MF10L was designed to offer these qualities for smaller cars and was only offered in 15&quot; diameters and a 4x100 bolt pattern.",
    "brand": "Mugen",
    "model": "MF10L",
    "manufacturer": "Rays Co., Ltd.",
    "year_start": "2001",
    "year_end": "2003",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "Split 5 Spoke",
    "link": "https://web.archive.org/web/20010419080349/http://www.mugen-honda.co.jp/lineup/wheel/wheel.htm#%EF%BC%AD%EF%BC%A6%EF%BC%91%EF%BC%90",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg"],
    "sizes": [
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+45", "colors": "White, Diamond Cut/Gunmetal"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+40", "colors": "White"}
    ],
    "related": ["GKHP1BHIO41L"]
  },
  {
    "id": "WJBPJCMTHH88",
    "shortname": "New Rayton EuroMagic GT-05Air",
    "description": "New Rayton's EuroMagic series of wheels combines a cast disk with a flow forming process to form the rim, providing a balance of high strength, light weight, and low cost.",
    "brand": "New Rayton",
    "model": "EuroMagic GT-05Air",
    "manufacturer": "Unverified",
    "year_start": "2005",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "5 Spoke",
    "link": "https://web.archive.org/web/20050415010055/http://www.newrayton.co.jp/wheel/euro_racing_st_05air/index.html",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+48", "colors": "Silver, Gold"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+38/+52", "colors": "Silver, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+24/+34/+38/+45", "colors": "Silver, Gold"},
      {"diameter": "18", "width": "9.5", "pcd": "5x114.3", "offsets": "+15/+25/+35/+45", "colors": "Silver, Gold"}
    ],
    "related": []
  },
  {
    "id": "TGKY3WIFFEH7",
    "shortname": "New Rayton EuroMagic GT-08F",
    "description": "New Rayton's EuroMagic series of wheels combines a cast disk with a flow forming process to form the rim, providing a balance of high strength, light weight, and low cost. Designed by Blest and sold under the EuroMagic brand as well as relabeled and sold by Bridgestone as the <a onclick='loadDetails(&quot;NROW8INOVB8S&quot;)'>Down Hill Special ae081</a>.",
    "brand": "New Rayton",
    "model": "EuroMagic GT-08F",
    "manufacturer": "Unverified",
    "year_start": "Unverified",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "8 Spoke",
    "link": "https://web.archive.org/web/20051104010611/http://www.newrayton.co.jp/wheel/euro_racing_gt_08f/index.html",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+48", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+40/+48/+52", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "17", "width": "8.5", "pcd": "5x100", "offsets": "+48", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+30/+40/+48", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+38/+48/+54", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x100", "offsets": "+45", "colors": "Silver, Gunmetal, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+38/+45", "colors": "Silver, Gunmetal, Gold"}
    ],
    "related": ["NROW8INOVB8S"]
  },
  {
    "id": "ZACE9Q0VK89O",
    "shortname": "Revowin PS-05",
    "description": "Manufactured by Tan-ei-sya for Puma Co., Ltd. and sold through Autobacs in Toyama Prefecture. The PS-05 is a rebranded <a onclick='loadDetails(&quot;XUN1UOX4TSJA&quot;)'>Southern Ways S-05</a>, offered in sizes catering to smaller cars and heavily used in Japanese Motorsports series including: Yaris Cup, All Japan Rally Championship, TGR Rally Challenge, VITA Race Series, and more.",
    "brand": "Revowin",
    "model": "PS-05",
    "manufacturer": "Tan-ei-sya Co., Ltd.",
    "year_start": "2012",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "Split 5 Spoke",
    "link": "https://web.archive.org/web/20240419050357/www.autobacs-toyama.com/revowin",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg"],
    "sizes": [
      {"diameter": "15", "width": "6.0", "pcd": "4x100", "offsets": "+39", "colors": "Racing White, Silver, Carbon Black , Black, Bronze, Gold, Blue, Red"},
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+37", "colors": "Racing White, Silver, Carbon Black , Black, Bronze, Gold, Blue, Red"},
      {"diameter": "15", "width": "6.5", "pcd": "5x100", "offsets": "+35", "colors": "Racing White, Silver, Carbon Black , Black, Bronze, Gold, Blue, Red"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+35/+48", "colors": "Racing White, Silver, Carbon Black , Black, Bronze, Gold, Blue, Red"}
    ],
    "related": ["XUN1UOX4TSJA"]
  },
  {
    "id": "XUN1UOX4TSJA",
    "shortname": "Southern Ways S-05",
    "description": "Manufactured by Tan-ei-sya and sold by its subsidiary ijak under the Southern Way brand until their rebrand in 2008 to TWS. The S-05 implemented wheel design and manufacturing technology that Tan-ei-sya developed while making wheels for F1 resulting in an incredibly strong and lightweight wheel that was widely used across many race series in Japan. This wheel has been sold by numerous other brands - including Car Life Revolution K-One K-01 and <a onclick='loadDetails(&quot;ZACE9Q0VK89O&quot;)'>Revowin PS-05</a>.",
    "brand": "Southern Ways",
    "model": "S-05",
    "manufacturer": "Tan-ei-sya Co., Ltd.",
    "year_start": "2004",
    "year_end": "2009",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "Split 5 Spoke",
    "link": "https://web.archive.org/web/20060509014028/http://www.ijak.co.jp/HPcatalog/s05size.html",
    "images": ["01.jpg","02.jpg"],
    "sizes": [
      {"diameter": "15", "width": "5.5", "pcd": "4x100", "offsets": "+38", "colors": "White, Silver, Gold"},
      {"diameter": "15", "width": "6.0", "pcd": "4x100", "offsets": "+39", "colors": "White, Silver, Gold"},
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+37", "colors": "White, Silver, Gold"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+35/+45/+48", "colors": "White, Silver, Gold"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+42", "colors": "White, Silver, Gold"},
      {"diameter": "16", "width": "7.5", "pcd": "5x114.3", "offsets": "+45", "colors": "White, Silver, Gold"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+48", "colors": "White, Silver, Gold"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+35/+45", "colors": "White, Silver, Gold"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+42", "colors": "White, Silver, Gold"},
      {"diameter": "17", "width": "8.5", "pcd": "5x100", "offsets": "+48", "colors": "White, Silver, Gold"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+35", "colors": "White, Silver, Gold"},
      {"diameter": "17", "width": "9.5", "pcd": "5x114.3", "offsets": "+37", "colors": "White, Silver, Gold"},
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+49", "colors": "White, Silver, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x100", "offsets": "+48", "colors": "White, Silver, Gold"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+20/+35", "colors": "White, Silver, Gold"},
      {"diameter": "18", "width": "9.5", "pcd": "5x114.3", "offsets": "+20/+35", "colors": "White, Silver, Gold"}
    ],
    "related": ["ZACE9Q0VK89O"]
  },
  {
    "id": "7AKI6FXXGMUE",
    "shortname": "Starform Real Racing Model II",
    "description": "When Starform decided to start producing lightweight forged wheels they looked to Tan-ei-sya for manufacturing. They followed up on the <a onclick='loadDetails(&quot;XEPK9WYCWZ9G&quot;)'>Real Racing R2</a> with the aptly named Real Racing Model II.",
    "brand": "Starform",
    "model": "Real Racing Model II",
    "manufacturer": "Tan-ei-sya Co., Ltd.",
    "year_start": "Unverified",
    "year_end": "2003",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "Split 6 Spoke",
    "link": "https://web.archive.org/web/20040101121118fw_/http://www.starform-jp.com/fr_model2_2.html",
    "images": ["01.jpg","02.jpg","03.jpg"],
    "sizes": [
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+35/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "15", "width": "7.0", "pcd": "4x114.3", "offsets": "+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+35/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "7.5", "pcd": "4x114.3", "offsets": "+32/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+32/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+38/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+30/+38/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "9.5", "pcd": "5x114.3", "offsets": "+38", "colors": "White, Gunmetal, Black"}
    ],
    "related": ["XEPK9WYCWZ9G"]
  },
  {
    "id": "XEPK9WYCWZ9G",
    "shortname": "Starform Real Racing R2",
    "description": "When Starform decided to start producing lightweight forged wheels they looked to Tan-ei-sya for manufacturing. The Real Racing R2 originally launched in just one diameter - 15 inch - but 17 inch options were quickly added to the lineup in 2000.",
    "brand": "Starform",
    "model": "Real Racing R2",
    "manufacturer": "Tan-ei-sya Co., Ltd.",
    "year_start": "1999",
    "year_end": "2003",
    "origin": "Japan",
    "construction": "1 Piece - Forged",
    "style": "5 Spoke",
    "link": "https://web.archive.org/web/20031229230549fw_/http://www.starform-jp.com/fr_R2_2.html",
    "images": ["01.jpg","02.jpg"],
    "sizes": [
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+34/+40", "colors": "White, Gunmetal, Black"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+39/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "15", "width": "7.0", "pcd": "4x114.3", "offsets": "+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+39/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "7.5", "pcd": "4x114.3", "offsets": "+32/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+32/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+30/+38/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+30/+38/+45", "colors": "White, Gunmetal, Black"},
      {"diameter": "17", "width": "9.5", "pcd": "5x114.3", "offsets": "+15/+23/+38", "colors": "White, Gunmetal, Black"}
    ],
    "related": ["7AKI6FXXGMUE"]
  },
  {
    "id": "IPL5GT7KH9V1",
    "shortname": "Uras NS-01",
    "description": "Originally manufactured for Doall as the CST D-Spec. Uras offered this Nismo LMGT4 inspired wheel as the NS-01 in sizes suitable for S-chassis Nissans.",
    "brand": "Uras",
    "model": "NS-01",
    "manufacturer": "Unverified",
    "year_start": "2004",
    "year_end": "2007",
    "origin": "Unverified",
    "construction": "1 Piece - Cast",
    "style": "5 Spoke",
    "link": "https://web.archive.org/web/20070504060720/http://www.uras.co.jp:80/syohin/wheel.html",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg"],
    "sizes": [
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+30", "colors": "Silver, Black, Chrome"},
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+30", "colors": "Silver, Black, Chrome"},
      {"diameter": "17", "width": "9.5", "pcd": "5x114.3", "offsets": "+15", "colors": "Silver, Black, Chrome"}
    ],
    "related": []
  },
  {
    "id": "214UPUFONY13",
    "shortname": "Uras NS-02",
    "description": "Manufactured by Futek and sold by a number of companies, Uras offered this cast wheel as the NS-02 in sizes suitable for S-chassis Nissans.",
    "brand": "Uras",
    "model": "NS-02",
    "manufacturer": "Futex Alloy (Changshu) Co., Ltd",
    "year_start": "2007",
    "year_end": "2007",
    "origin": "China",
    "construction": "1 Piece - Cast",
    "style": "Split 6 Spoke",
    "link": "https://web.archive.org/web/20070504060427/http://www.uras.co.jp:80/syohin/wheel_ns02.html",
    "images": ["01.jpg"],
    "sizes": [
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+30", "colors": "Chrome"},
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+15", "colors": "Chrome"}
    ],
    "related": []
  },
  {
    "id": "ZG3NYKP280MJ",
    "shortname": "WedsSport TC-05",
    "description": "The WedsSport TC Series has long been WedsSport's flagship line of wheels and it all started with the release of the TC-05 in 1993.",
    "brand": "Weds",
    "model": "WedsSport TC-05",
    "manufacturer": "Asahi Tec Co., Ltd",
    "year_start": "1993",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "8 Spoke",
    "link": "https://web.archive.org/web/20020808141524/http://weds.co.jp/products/wedssport/tc-05/index.htm",
    "images": ["01.jpg"],
    "sizes": [
      {"diameter": "14", "width": "6.0", "pcd": "4x100", "offsets": "+20/+29/+35/+39", "colors": "White"},
      {"diameter": "14", "width": "6.5", "pcd": "4x100", "offsets": "+24/+30/+39/+43", "colors": "White"},
      {"diameter": "15", "width": "6.0", "pcd": "4x100", "offsets": "+30/+37", "colors": "White"},
      {"diameter": "15", "width": "6.0", "pcd": "4x114.3", "offsets": "+30/+37", "colors": "White"},
      {"diameter": "15", "width": "6.0", "pcd": "5x114.3", "offsets": "+37", "colors": "White"},
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+15/+25/+30/+38/+43", "colors": "White"},
      {"diameter": "15", "width": "6.5", "pcd": "4x114.3", "offsets": "+15/+25/+43", "colors": "White"},
      {"diameter": "15", "width": "6.5", "pcd": "5x114.3", "offsets": "+25/+30/+38", "colors": "White"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+36/+40", "colors": "White"},
      {"diameter": "15", "width": "7.0", "pcd": "4x114.3", "offsets": "+19/+40/+49", "colors": "White"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+31/+40", "colors": "White"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+33/+42/+48", "colors": "White"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+33/+42/+48", "colors": "White"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+33/+42/+48", "colors": "White"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+33/+42/+48", "colors": "White"},
      {"diameter": "16", "width": "8.0", "pcd": "4x100", "offsets": "+29/+34", "colors": "White"},
      {"diameter": "16", "width": "8.0", "pcd": "4x114.3", "offsets": "+29/+34", "colors": "White"},
      {"diameter": "16", "width": "8.0", "pcd": "5x100", "offsets": "+29/+34", "colors": "White"},
      {"diameter": "16", "width": "8.0", "pcd": "5x114.3", "offsets": "+29/+34", "colors": "White"},
      {"diameter": "17", "width": "7.0", "pcd": "4x100", "offsets": "+35/+40", "colors": "Pearl White"},
      {"diameter": "17", "width": "7.0", "pcd": "4x108", "offsets": "+35", "colors": "Pearl White"},
      {"diameter": "17", "width": "7.0", "pcd": "4x114.3", "offsets": "+40", "colors": "Pearl White"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+35", "colors": "Pearl White"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+35", "colors": "Pearl White"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+32", "colors": "White"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+40", "colors": "White"},
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+20/+37", "colors": "White"}
    ],
    "related": []
  },
  {
    "id": "HFVKRVT1CDST",
    "shortname": "WedsSport TC-005",
    "description": "The WedsSport TC Series has long been WedsSport's flagship line of wheels. Weds followed up the original TC-05 with the TC-005 which saw great success at every level of motorsports.",
    "brand": "Weds",
    "model": "WedsSport TC-005",
    "manufacturer": "Asahi Tec Co., Ltd",
    "year_start": "2000",
    "year_end": "2004",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "Split 5 Spoke",
    "link": "https://web.archive.org/web/20020808141524/http://weds.co.jp/products/wedssport/tc-005/index.htm",
    "images": ["01.jpg","02.jpg"],
    "sizes": [
      {"diameter": "14", "width": "6.0", "pcd": "4x100", "offsets": "+20/+25/+29", "colors": "White"},
      {"diameter": "15", "width": "6.5", "pcd": "4x95.3", "offsets": "+11", "colors": "Silver"},
      {"diameter": "15", "width": "6.5", "pcd": "4x100", "offsets": "+15/+25/+30/+38/+43", "colors": "White"},
      {"diameter": "15", "width": "6.5", "pcd": "4x114.3", "offsets": "+15/+25/+43", "colors": "White"},
      {"diameter": "15", "width": "6.5", "pcd": "5x114.3", "offsets": "+25/+30/+38", "colors": "White"},
      {"diameter": "15", "width": "7.0", "pcd": "4x100", "offsets": "+19/+25/+36/+40", "colors": "White"},
      {"diameter": "15", "width": "7.0", "pcd": "4x114.3", "offsets": "+19/+31/+40", "colors": "White"},
      {"diameter": "15", "width": "7.0", "pcd": "5x114.3", "offsets": "+19/+31/+40", "colors": "White"},
      {"diameter": "15", "width": "7.5", "pcd": "4x100", "offsets": "+41/+45", "colors": "White"},
      {"diameter": "15", "width": "7.5", "pcd": "4x114.3", "offsets": "+24/+36/+45", "colors": "White"},
      {"diameter": "15", "width": "7.5", "pcd": "5x114.3", "offsets": "+36/+45", "colors": "White"},
      {"diameter": "16", "width": "7.0", "pcd": "4x100", "offsets": "+33/+37/+42", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "4x114.3", "offsets": "+30/+42", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "5x100", "offsets": "+45", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.0", "pcd": "5x114.3", "offsets": "+30/42", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.5", "pcd": "5x100", "offsets": "+45", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "7.5", "pcd": "5x114.3", "offsets": "+14/+29/+45", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "8.0", "pcd": "4x95.3", "offsets": "+10", "colors": "Silver"},
      {"diameter": "16", "width": "8.0", "pcd": "4x100", "offsets": "+38", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "8.0", "pcd": "4x114.3", "offsets": "+34", "colors": "White, Gunmetal"},
      {"diameter": "16", "width": "8.0", "pcd": "5x114.3", "offsets": "+25/+34/+42", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "4x100", "offsets": "+33/+38", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "4x114.3", "offsets": "+40", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "5x100", "offsets": "+40/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.0", "pcd": "5x114.3", "offsets": "+33/+40/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "4x100", "offsets": "+41/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "4x114.3", "offsets": "+30/+41", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "5x100", "offsets": "+41/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "7.5", "pcd": "5x114.3", "offsets": "+28/+41/+48", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "8.0", "pcd": "5x100", "offsets": "+32/+42", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "8.0", "pcd": "5x114.3", "offsets": "+32/+38/+42", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "8.5", "pcd": "5x114.3", "offsets": "+25/+30/+38", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "9.0", "pcd": "5x114.3", "offsets": "+10/+25/+34/+42", "colors": "White, Gunmetal"},
      {"diameter": "17", "width": "9.5", "pcd": "5x114.3", "offsets": "+12/+25/+30/+35/+40", "colors": "White, Gunmetal"},
      {"diameter": "18", "width": "7.5", "pcd": "5x100", "offsets": "+48", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+33/+43/+48", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "8.0", "pcd": "5x114.3", "offsets": "+31/+37/+42", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+32/+44/+53", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "9.0", "pcd": "5x114.3", "offsets": "+15/+34/+39/+44", "colors": "Silver, Gunmetal"},
      {"diameter": "18", "width": "10.0", "pcd": "5x114.3", "offsets": "+18/+44", "colors": "Silver, Gunmetal"}
    ],
    "related": []
  },
  {
    "id": "CHSBALEGASCX",
    "shortname": "Yokohama Connoisseur No. 51C",
    "description": "Yokohama's Connoisseur brand started with the release of the No. 51C. The brand was developed to provide a product suitable for Japanese luxury sedans - such as the Celsior and Cima - with the goal of looking not overly dressed up, but rather to be comparable to European super luxury sedans that pursue driving above all else.",
    "brand": "Yokohama",
    "model": "Connoisseur No. 51C",
    "manufacturer": "Enkei Co., Ltd.",
    "year_start": "2002",
    "year_end": "Unverified",
    "origin": "Japan",
    "construction": "1 Piece - Cast",
    "style": "5 Spoke",
    "link": "https://web.archive.org/web/20060820145351/http://www.yokohamatire.jp/yrc/japan/wheel/brand/co_51c/index.html",
    "images": ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg","06.jpg","07.jpg","08.jpg","09.jpg","10.jpg","11.jpg"],
    "sizes": [
      {"diameter": "18", "width": "7.5", "pcd": "5x114.3", "offsets": "+40/+45/+50", "colors": "Silver, Bronze, Chrome"},
      {"diameter": "18", "width": "8.5", "pcd": "5x114.3", "offsets": "+31/+38/+45", "colors": "Silver, Bronze, Chrome"},
      {"diameter": "18", "width": "9.5", "pcd": "5x114.3", "offsets": "+40", "colors": "Silver, Bronze, Chrome"},
      {"diameter": "19", "width": "8.5", "pcd": "5x114.3", "offsets": "+31/+38/+44", "colors": "Silver, Bronze, Chrome"},
      {"diameter": "19", "width": "9.5", "pcd": "5x114.3", "offsets": "+40", "colors": "Silver, Bronze, Chrome"},
      {"diameter": "20", "width": "9.0", "pcd": "5x114.3", "offsets": "+32/+42", "colors": "Silver, Bronze, Chrome"},
      {"diameter": "20", "width": "10.0", "pcd": "5x114.3", "offsets": "+39/+44", "colors": "Silver, Bronze, Chrome"}
    ],
    "related": []
  }
]